### ISSUE TITLE
Pantalla Listado de compras

### ISSUE THREAD

**Issue by MJoaaquin** [fiqus/compras-comunitarias#48]
Listar las compras activas y las proximas compras

**Comment by MJoaaquin** [comment]
![image](https://user-images.githubusercontent.com/25573401/153008946-fc6baffa-4049-417b-a26b-3e9fa2033ba6.png)

**Comment by MJoaaquin** [comment]
se comento de que al principio no haya login y solo mandar un link a la compra (como venimos haciendo con los formularios) porque lo supongo que esta pantalla **no es tan prioritaria** y habría que encarar primero las pantallas de flujo de compra. **Consultarlo**

**Comment by JeronimoC23** [comment]
![image](https://user-images.githubusercontent.com/66791971/153886215-2959521d-d9b8-41ed-8b33-f24ce2b708db.png)

**Comment by ezequielleiter** [comment]
![image](https://user-images.githubusercontent.com/89612364/154974237-9e7f1770-dff4-4e4f-83a9-a8536d2db513.png)

**Comment by ezequielleiter** [comment]
![image](https://user-images.githubusercontent.com/89612364/154974344-829b20c9-b45a-4998-af9f-ba4078eef16e.png)

**Comment by ezequielleiter** [comment]
Ahi estaría el mokaup  de las compras activas
