### ISSUE TITLE
Pantalla listado de productos de una compra

### ISSUE THREAD

**Issue by MJoaaquin** [fiqus/compras-comunitarias#49]
Pantalla en donde el usuario realiza la compra

**Comment by MJoaaquin** [comment]
![image](https://user-images.githubusercontent.com/25573401/153009971-9325ca47-ee64-4fd4-bf33-ff7f403c2d52.png)

**Comment by JeronimoC23** [comment]
![image](https://user-images.githubusercontent.com/66791971/153886120-03df0233-e523-4992-aea5-50ad9eb6adfe.png)

**Comment by JeronimoC23** [comment]
web 
![image](https://user-images.githubusercontent.com/66791971/153886336-fd250726-2e41-4c0a-909a-9b9a94a54f07.png)

**Comment by ezequielleiter** [comment]
![image](https://user-images.githubusercontent.com/89612364/154974947-d0780a76-1371-420b-ae07-c07f3dba63e8.png)

**Comment by ezequielleiter** [comment]
![image](https://user-images.githubusercontent.com/89612364/154975096-048eb1ce-7e3d-4d72-ae53-45b7d27095e0.png)
