### ISSUE TITLE
Pantalla de Compras Activas  no Hardcodeada

### ISSUE THREAD

**Issue by MJoaaquin** [fiqus/compras-comunitarias#69]

**Comment by JeronimoC23** [comment]
Por algun motivo hace 3 request a la api :
![image](https://user-images.githubusercontent.com/66791971/156647383-0558fab5-976c-4e7a-9e8c-f5b6854e1d9f.png)
en la primera no manda la authorization:
![image](https://user-images.githubusercontent.com/66791971/156647601-2dfb60eb-1b23-40c0-a210-b3bd6809962c.png)
 pero solo en la 2da y en la tercera manda el authorization pero ya no tiene el token :
![image](https://user-images.githubusercontent.com/66791971/156647477-bd3608cd-4a5b-4f1e-a340-6f843a8cc010.png)

**Comment by JeronimoC23** [comment]
solucion: 
Estaba devolviendo un object en header, asique necesitaba acceder a su propiedad token
![image](https://user-images.githubusercontent.com/66791971/156807779-388d1761-6045-49b1-99c4-f564ecd051f0.png)
